name: README CI Suggestions

on:
  pull_request:
    branches: [main]

jobs:
  readme-suggestions:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cjlludwig/ReReadme@v0.0.10
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          verbose: 'true'
